version: '3.1'

services:

  mongo:
    image: mongo:5.0
    restart: always
    mem_limit: 512m
    cpus: 0.5
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: fhasgkr867fa654
    ports:
      - 27017:27017
    volumes:
      - ./volumes/mongodb:/data/db
  
  http-server:
    build: backend/agent-manager/.
    image: agent-manager:v1
    restart: always
    cpus: 0.5
    ports:
      - 8080:8080
    depends_on: 
      - mongo

  nats-server:
    build: project-infraestructure/messaging/.
    image: nats-server:v1
    restart: always
    cpus: 0.5
    ports:
      - 4222:4222
      - 8222:8222
  
  license-manager:
    build: backend/licensing-manager/.
    image: license-manager:v1
    restart: always
    cpus: 0.5
    depends_on: 
      - mongo
      - nats-server
