// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"http-models-server/cmd/config"
	"http-models-server/domain/usecases/trainingUsecase"
	"http-models-server/infraestructure/app"
	"http-models-server/infraestructure/database"
	"http-models-server/infraestructure/database/repositories"
	"http-models-server/infraestructure/server"
)

// Injectors from wire.go:

func CreateApp() *app.Application {
	engine := server.NewServer()
	env := config.NewEnvironmentsSpecification()
	databaseImp := database.NewDatabaseImplementation(env)
	trainingRepository := repositories.NewTrainingRepository(databaseImp)
	trainingUsecase := trainingusecase.NewTrainingUsecase(trainingRepository)
	application := app.NewApplication(engine, env, databaseImp, trainingUsecase)
	return application
}
