basePath: /api/v1
info:
  contact: {}
  description: This microservice connects the front-end and is the core of the project
  title: Backend
  version: 1.0.0
paths:
  /:
    get:
      consumes:
      - application/json
      description: This endpoint does not do nothing
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
        "401":
          description: Unauthorized
          schema:
            type: string
      summary: Index
      tags:
      - Hibot
swagger: "2.0"
