// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/LuisDiazM/goCore/domain/usecases"
	"github.com/LuisDiazM/goCore/infraestructure/databases"
)

import (
	_ "github.com/LuisDiazM/goCore/docs"
)

// Injectors from wire.go:

func CreateApp() *Application {
	databaseGateway := databases.NewDatabaseGatewayImp()
	channelsUsecase := usecases.NewChannelUsecase(databaseGateway)
	trainingUseCase := usecases.NewTrainingUsecase(databaseGateway)
	application := NewApplication(databaseGateway, channelsUsecase, trainingUseCase)
	return application
}
